name: CarnavalDerDierenApp
options:
  minimumXcodeGenVersion: 2.38.0
  deploymentTarget:
    iOS: 16.0
settings:
  base:
    PRODUCT_BUNDLE_IDENTIFIER: nl.followamuse.carnavalderdieren
    SWIFT_VERSION: 5.0
targets:
  CarnavalDerDierenApp:
    type: application
    platform: iOS
    sources:
      - path: CarnavalDerDierenApp
    resources:
      - path: CarnavalDerDierenApp/Resources
    settings:
      base:
        INFOPLIST_FILE: CarnavalDerDierenApp/Info.plist
        PRODUCT_NAME: Carnaval der Dieren
    info:
      path: CarnavalDerDierenApp/Info.plist
      properties:
        CFBundleDisplayName: Carnaval der Dieren
        UILaunchScreen: {}
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
